# Generated by Django 5.1.7 on 2025-03-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_on', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketstatus',
            name='color',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(blank=True, default='Novo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='move_on.ticketstatus'),
        ),
    ]
