# Generated by Django 5.1.7 on 2025-04-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_on', '0004_category_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Ação'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='action_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fim'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='action_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Início'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='tickets/audios/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='log',
            field=models.TextField(blank=True, verbose_name='Log de Alterações'),
        ),
    ]
