# Generated by Django 5.1.7 on 2025-04-02 00:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move_on', '0005_ticket_action_date_ticket_action_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='action_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='action_end_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='action_start_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.CreateModel(
            name='TicketAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.IntegerField(verbose_name='Número da Ação')),
                ('description', models.TextField(verbose_name='Descrição da Ação')),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Ação')),
                ('action_start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Início')),
                ('action_end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Fim')),
                ('audio', models.FileField(blank=True, null=True, upload_to='tickets/audios/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tickets/images/')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='move_on.team')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='move_on.ticket')),
            ],
            options={
                'db_table': 'ticket_actions',
                'ordering': ['action_number'],
            },
        ),
    ]
