# Generated by Django 5.1.7 on 2025-03-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatroom',
            table='chatrooms',
        ),
        migrations.AlterModelTable(
            name='chatticket',
            table='chat_tkts',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
    ]
