# Generated by Django 5.1.7 on 2025-03-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_table_alter_chatticket_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
