# Generated by Django 5.1.7 on 2025-03-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_message',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
