# Generated by Django 5.1.7 on 2025-03-26 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_last_message_chatroom_last_message'),
        ('move_on', '0002_remove_ticketstatus_color_alter_ticket_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ticket',
            field=models.ForeignKey(db_column='ticket_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='move_on.ticket'),
            preserve_default=False,
        ),
    ]
