# Generated by Django 5.1.7 on 2025-03-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='name',
        ),
    ]
