# Generated by Django 5.1.7 on 2025-04-02 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lunch_break_minutes', models.PositiveIntegerField(default=0)),
                ('work_days', models.JSONField(default=list)),
                ('max_weekly_hours', models.PositiveIntegerField(default=40)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_type', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('night', 'Noite')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('day_off', 'Folga'), ('absent', 'Ausente')], default='active', max_length=10)),
                ('override_day_off', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workschedule',
                'ordering': ['date', 'start_time'],
                'unique_together': {('worker', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
